name: Integration

on:
  workflow_dispatch:
    inputs:
      snap-channel:
        description: Snap Store channel
      mac-package:
        description: macOS package URL
      win-package:
        description: Windows package URL

jobs:
  GetMatrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      bors-matrix: ${{ steps.set-matrix.outputs.bors-matrix }}

    steps:
    - name: Determine job matrix
      id: set-matrix
      run: |
        set -euo pipefail

        MATRIX=""

        if [ -n '${{ github.event.inputs.snap-channel }}' ]; then
          MATRIX+='{"os": "Linux", "driver": "qemu"}'
          MATRIX+='{"os": "Linux", "driver": "lxd"}'
        fi

        if [ -n '${{ github.event.inputs.mac-package }}' ]; then
          MATRIX+='{"os": "macOS", "driver": "hyperkit"}'
        fi

        if [ -n '${{ github.event.inputs.win-package }}' ]; then
          MATRIX+='{"os": "Windows", "driver": "hyperv"}'
        fi

        echo "${MATRIX}" | jq -cs '{"include": . }' | awk '{ print "::set-output name=matrix::" $0 }'

  CI:
    needs: GetMatrix

    runs-on: testflinger

    timeout-minutes: 30

    strategy:
      matrix: ${{ fromJSON(needs.GetMatrix.outputs.matrix) }}

    env:
      TESTFLINGER_FILE: testflinger-${{ matrix.os }}-${{ matrix.driver }}.yaml

    steps:
    - name: Write the testflinger job
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: ${{ env.TESTFLINGER_FILE }}
        write-mode: overwrite
        contents: |
          job_queue: vmware-fusion
          output_timeout: 2400
          provision_data:
            ${{ matrix.os == 'Linux' && 'vmx: /Users/michal/Virtual Machines.localized/linux.vmwarevm/linux.vmx' || '' }}
            ${{ matrix.os == 'macOS' && 'vmx: /Users/michal/Virtual Machines.localized/macos-11.vmwarevm/macos-11.vmx' || '' }}
            ${{ matrix.os == 'Windows' && 'vmx: /Users/michal/Virtual Machines.localized/windows-10.vmwarevm/windows-10.vmx' || '' }}
            snapshot: Testflinger
            ${{ matrix.os == 'Linux' && 'image_url: http://cloud-images.ubuntu.com/releases/groovy/release/ubuntu-20.10-server-cloudimg-amd64.img' || '' }}
            vmx_config:
              ${{ matrix.os == 'Linux' && 'memsize: 2048' || '' }}
              memsize: 2048
              vhv.enable: true
              vpmc.enable: true

          test_data:
            ${{ matrix.os == 'Windows' && 'test_username: user' || '' }}
            test_cmds: |
              set -xeuo pipefail

              MP=multipass
              [ '${{ matrix.os }}' == 'macOS' ] && MP=/usr/local/bin/multipass

              function _run() {{
                ssh ${{ '${{SSH_OPTS}} "${{DEVICE_USER}}@${{DEVICE_IP}}" -- "${{@}}"' }}
              }}

              # Retry $1 times, with $2 seconds in between tries
              function _retry() {{
                  tries=$1
                  interval=$2
                  shift 2
                  for try in $( seq $tries ); do
                      RC=0
                      ${{ '"${{@}}"' }} || RC=$?
                      [ $RC -eq 0 -o $try -eq $tries ] && return $RC
                      sleep $interval;
                  done
              }}

              # Retry $1 times, with $2 seconds in between tries, until $3 greps
              function _retry_grep() {{
                  tries=$1
                  interval=$2
                  pattern=$3
                  shift 3
                  for try in $( seq $tries ); do
                      RC=0
                      ${{ '"${{@}}"' }} | grep --quiet -e "$pattern" || RC=$?
                      [ $RC -eq 0 -o $try -eq $tries ] && return $RC
                      sleep $interval;
                  done
              }}

              # Log journal entries on bad exit
              function _exit() {{
                RC=$?
                if [ '${{ matrix.os }}' == 'Linux' ]; then
                  [ $RC -eq 0 ] || _run sudo journalctl -u snap.multipass*
                elif [ '${{ matrix.os }}' == 'macOS' ]; then
                  [ $RC -eq 0 ] || _run sudo cat /Library/Logs/Multipass/multipassd.log
                fi
              }}
              trap _exit EXIT

              function _ps() {{
                _run powershell -noprofile -noninteractive -command ${{ '${{@}}' }}
              }}

              if [ '${{ matrix.os }}' == 'Linux' ]; then
                # Give snapd time to settle
                _retry 5 30 _run sudo snap install multipass --channel ${{ github.event.inputs.snap-channel }}

              elif [ '${{ matrix.os }}' == 'macOS' ]; then
                _run curl --location --output multipass.pkg ${{ github.event.inputs.mac-package }}
                _run sudo installer -dumplog -target / -pkg multipass.pkg

              elif [ '${{ matrix.os }}' == 'Windows' ]; then
                _ps "(New-Object System.Net.WebClient).DownloadFile('${{ github.event.inputs.win-package }}', 'multipass-installer.exe')"
                _run .\\multipass-installer.exe /S

                _ps "Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All -NoRestart"
                _ps "Restart-Computer -Force"
                sleep 60
              fi

              if [ '${{ matrix.driver }}' == 'lxd' ]; then
                _run sudo snap connect multipass:lxd lxd
                _run sudo lxd init --auto
                _run sudo multipass set local.driver=lxd
              fi

              # Give multipassd time to settle (#1995)
              _retry_grep 12 5 "\w,lts\W" _run $MP find
              sleep 10

              _run $MP start --timeout 600

              _run $MP list

              _run $MP exec primary -- uname -a

    - name: Submit the job
      id: submit
      run: |
        JOB_ID=$( testflinger-cli submit --quiet ${TESTFLINGER_FILE} )
        echo "::set-output name=job-id::${JOB_ID}"

    - name: Poll the job and get the result
      run: |
        testflinger-cli poll "${{ steps.submit.outputs.job-id }}"
        [ "$( testflinger-cli results ${{ steps.submit.outputs.job-id}} | jq -r .test_status )" -eq 0 ]

    - name: Cancel the job
      if: ${{ cancelled() && steps.submit.outputs.job-id != '' }}
      run: |
       testflinger-cli cancel "${{ steps.submit.outputs.job-id }}"
